on:
  push:
    branches: [master]
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.6.0

      - name: Setup JAVA 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Debug Base64 String
        run: |
          echo "${{ secrets.SIGNING_KEY_STORE_BASE64 }}"

      - name: Create /tmp directory
        run: mkdir -p /tmp

      - name: Decode Keystore
        run: |
          echo "${{ secrets.SIGNING_KEY_STORE_BASE64 }}" | base64 --decode > $HOME/keystore.jks
          chmod 600 $HOME/keystore.jks
          ls -l $HOME/keystore.jks

      - name: Build Release apk
        env:
          SIGNING_KEY_STORE_PATH: $HOME/keystore.jks
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        run: ./gradlew assembleRelease

      - name: Capture Gradle Output
        run: ./gradlew assembleRelease --debug

      - name: List files for debugging
        run: ls -R app/build/outputs/apk/release/

      - name: Upload Release Build to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-artifacts
          paths: |
            app/build/outputs/apk/release/

      - name: Create Github Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          prerelease: false
          files: |
            app/build/outputs/apk/release/*.apk